#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --dbname="$POSTGRES_DB" --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $GIS_USER WITH PASSWORD '$GIS_PASSWORD';
    CREATE DATABASE $GIS_DB ENCODING 'UTF8' OWNER $GIS_USER;
EOSQL
